// aucune erreur quand la valeur de retour d'un appel n'est pas utilisée

importe Support

principale :: fonc () -> z32
{
    erreur_survenue := #exécute compile_script_erroné(«
    fonction :: fonc () -> z32
    {
        retourne 0
    }
    principale :: fonc () -> z32
    {
        ptr := fonction
        ptr()
        retourne 0
    }
    »)
    saufsi (erreur_survenue) {
        retourne 1
    }
    retourne 0
}
